<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="../css/style.css">


    <title>Sprint</title>
</head>

<body>
    
    <header>
        <a href="index.php">Accueil</a>
        <nav>
            <?php if (isset($_SESSION['user'])): ?>
            <a href="account.php" class="button">Compte</a>
           <form method="POST" action="logout.php">
             <button type="submit" name="logout" class="button">Déconnexion</button>
           </form>
        <?php else: ?>
            <a href="signin.php" class="button">Connectez-vous</a>
        <?php endif; ?>
            <a href="register.php">Inscription</a>
        </nav>
    </header>
    
    <main>
        
        <?php include "$template.phtml" ?>
        
    </main>
    <footer>
        <p>© Copyright 3WA</p>
    </footer>
</body>

</html>