<div class="signup">
    
    <h1>Inscription</h1>
    <div class="container">
        
        <form method="POST">
            
            <label for="username">Nom d'utilisateur :</label>
            <input type="text" id="username" name="username" required>
            
            <label for="email">Email :</label>
            <input type="text" id="email" name="email" required>
    
            <label for="new-password">Mot de passe :</label>
            <input type="password" id="new-password" name="password" required>
    <p>Votre mot de passe doit contenir 8 et 16 caractères, avec une majuscule et minuscule, 1 chiffre et 1 caractère spécial.</p>
            <button>s'inscrire</button>
        </form>
        <?php if (isset($error_message)): ?>
           <div class="error"> <?= $error_message ?> </div>
        <?php endif ?>
    </div>
</div>