<div class="signin">
    
    <h1>Connection</h1>
        <div class="container">
            <form method="post">
            
               <label for="username">Nom d'utilisateur :</label>
               <input type="text" id="username" name="username" required>

               <label for="password">Mot de passe :</label>
               <input type="password" id="password" name="password" required>

               <button>Se connecter</button>
            </form>
        </div>
</div>
    